### ISSUE TITLE
gitlab-runner reload fails on reload

### ISSUE THREAD

**Issue by flexoid** [riemers/ansible-gitlab-runner#39] opened 2019-03-26 13:31 UTC
Looks like `reload` is not supported by debian `gitlab-runner` service.

RUNNING HANDLER [riemers.gitlab-runner : reload_gitlab_runner] ***********************************************************************************************
fatal: [X.X.X.X]: FAILED! => {"changed": false, "msg": "Unable to reload service gitlab-runner: Failed to reload gitlab-runner.service: Job type reload is not applicable for unit gitlab-runner.service.\nSee system logs and 'systemctl status gitlab-runner.service' for details.\n"}

I think `restart` can be used instead.

**Comment by riemers** [comment] 2019-03-31 13:08
Could you verify and if so issue a PR? You can change the code locally on your site and do a inline edit here.

**Comment by heytrav** [comment] 2019-04-18 01:39
I can confirm this behaviour. 
```

RUNNING HANDLER [riemers.gitlab-runner : reload_gitlab_runner] ***************************************************************************************************************
fatal: [docker-testrunner01]: FAILED! => {"changed": false, "msg": "Unable to reload service gitlab-runner: Failed to reload gitlab-runner.service: Job type reload is not applicable for unit gitlab-runner.service.\nSee system logs and 'systemctl status gitlab-runner.service' for details.\n"}

```

**Comment by heytrav** [comment] 2019-04-18 02:23
After changing to the `restart` handler it seems to work.

**Comment by zaunerc** [comment] 2019-05-02 10:49
I can also confirm this issue and therefore would really like to see PR #41 merged in as soon as possible ;-) By the way. I am using Debian Stretch. Maybe the systemd service installed by the old `gitlab-ci-multi-runner` package did support the reload action. The systemd service installed by the newer `gitlab-runner` package definitely does not.

**Comment by riemers** [comment] 2019-05-09 21:49
since it is merged, i do believe we can close this one 👌

**Closed by riemers** 2019-05-09 21:49 UTC
